---
apiVersion: v1
kind: Service
metadata:
  name: myweb-app-service-prod
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: <<replace with static IP>>
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: my-app-prod
    environment: test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myweb-app-service-prod
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-app.kr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myweb-app-service-prod
                port:
                  number: 80
